# Generated by Django 5.2.6 on 2026-02-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='photo',
        ),
    ]
