# Generated by Django 5.2.6 on 2026-02-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_doctor_photo_remove_patient_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
