# Generated by Django 5.2.6 on 2026-02-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_appointment_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patients/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
    ]
