# Generated by Django 5.2.6 on 2026-02-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_doctor_image_patient_image_alter_doctor_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(help_text='Years of experience'),
        ),
    ]
